### ISSUE TITLE
Bug report - Loading model error

### ISSUE THREAD

**Issue by lemoner20** [snakers4/silero-vad#180]
## 🐛 Bug

Hello, when I load the vad model, this error as bellow,

## To Reproduce

```
>>> m = torch.jit.load('./files/silero_vad.jit')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pai/lib/python3.6/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: 
Unknown type name 'NoneType':
Serialized   File "code/__torch__/torch/nn/modules/conv.py", line 7
  bias : Optional[Tensor]
  training : bool
  _is_full_backward_hook : NoneType
                           ~~~~~~~~ <--- HERE
  transposed : bool
  _reversed_padding_repeated_twice : List[int]
```

```
>>> m = OnnxWrapper(f'./files/silero_vad.onnx')
---------------------------------------------------------------------------
InvalidGraph                              Traceback (most recent call last)
<ipython-input-18-3ba7ab68af4b> in <module>
----> 1 m = OnnxWrapper(f'./files/silero_vad.onnx')

~/.cache/torch/hub/snakers4_silero-vad_master/utils_vad.py in __init__(self, path)
     14         global np
     15         import onnxruntime
---> 16         self.session = onnxruntime.InferenceSession(path)
     17         self.session.intra_op_num_threads = 1
     18         self.session.inter_op_num_threads = 1

/home/lib/python3.6/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options, providers)
    156         self._path_or_bytes = path_or_bytes
    157         self._sess_options = sess_options
--> 158         self._load_model(providers or [])
    159         self._enable_fallback = True
    160         Session.__init__(self, self._sess)

/home/lib/python3.6/site-packages/onnxruntime/capi/session.py in _load_model(self, providers)
    175             raise TypeError("Unable to load from type '{0}'".format(type(self._path_or_bytes)))
    176 
--> 177         self._sess.load_model(providers)
    178 
    179         self._sess_options = self._sess.session_options

InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:Shape_0 : No Op registered for Shape with domain_version of 13
```

## Environment

```
onnxruntime-gpu: 1.4.0
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.9

Python version: 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.19.91-007.ali4000.alios7.x86_64-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB

Nvidia driver version: 440.64.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
```

**Comment by snakers4** [comment]
> onnxruntime-gpu: 1.4.0

I believe that we have not tested the GPU-version of ONNX runtime
Can you please try the CPU version?

> PyTorch version: 1.8.1+cu102

The current iteration of models work with PyTorch 1.9+ (I do not remember why, but something did not work prior, or maybe the compiler is only compatible in one direction).

**Comment by lemoner20** [comment]
Thanks for your reply. 

I try cpu-version `onnxruntime==1.6.0` and `pytorch==1.10.0`, now it works.

**Comment by snakers4** [comment]
Ok.
Looks like problem solved.
I will migrate this issue to discussions.
