### ISSUE TITLE
Bug report - [X]urllib.error.URLError: <urlopen error [Errno 2] No such file or directory> in https://pytorch.org/hub/snakers4_silero-vad_vad/

### ISSUE THREAD

**Issue by JamesSmith20** [snakers4/silero-vad#272]
## 🐛 Bug

Excuse me. I get this error when I study the example on the official site:https://pytorch.org/hub/snakers4_silero-vad_vad/. And I don't get answer although I google over 3 hours. So I submit the issue.
## To Reproduce

input 
```
import torch
torch.set_num_threads(1)

from IPython.display import Audio
from pprint import pprint
# download example
torch.hub.download_url_to_file('https://models.silero.ai/vad_models/en.wav', 'en_example.wav')

model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
                              model='silero_vad',
                              force_reload=True)

```

2.the cmd return
```
 D:\Instrument\Python\lib\site-packages\torch\hub.py:267: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to C:\Users\james/.cache\torch\hub\master.zip
Traceback (most recent call last):
  File "D:\Instrument\Python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\Instrument\Python\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Instrument\Python\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Instrument\Python\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Instrument\Python\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "D:\Instrument\Python\lib\http\client.py", line 975, in send
    self.connect()
  File "D:\Instrument\Python\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\Instrument\Python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Instrument\Python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\Instrument\Python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Instrument\Python\lib\site-packages\torch\hub.py", line 539, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "D:\Instrument\Python\lib\site-packages\torch\hub.py", line 211, in _get_cache_or_reload
    download_url_to_file(url, cached_file, progress=False)
  File "D:\Instrument\Python\lib\site-packages\torch\hub.py", line 597, in download_url_to_file
    u = urlopen(req)
  File "D:\Instrument\Python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Instrument\Python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\Instrument\Python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\Instrument\Python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\Instrument\Python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\Instrument\Python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

```

## Expected behavior

Make
```
model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
                              model='silero_vad',
                              force_reload=True)
```
run well. 

## Environment

```
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] (64-bit runtime)        
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060
Nvidia driver version: 522.06
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.13.0+cu117
[pip3] torchaudio==0.13.0
[pip3] torchvision==0.14.0
[conda] No relevant packages
```

**Comment by JamesSmith20** [comment]
Thanks for your response! The next context is my response.
Does this URL open from your PC? Did the zip file download?
---------------------------------------
The URL "https://github.com/snakers4/silero-vad/zipball/master" could open from my PC. And a file named "snakers4-silero-vad-v4.0-0-g82d199f.zip" has been downloaded. 
--------------------------------------------
Do all of these subfolders exist?
C:\Users\james\.cache\torch\hub just has a folder named "checkpoints" and a file named “trusted_list”. 
master.zip is not found in the path.
