### ISSUE TITLE
Torchhub is broken on pytorch-nightly or dev versions

### ISSUE THREAD

**Issue by NicolasHug** [snakers4/silero-vad#283]
The version check introduced here:

https://github.com/snakers4/silero-vad/blob/e7c4539106bbfa14b3e15dee6bf761375a3c85f1/hubconf.py#L19-L20

is valid for stable releases, but unfortunately fails on the pytorch-nightly versions strings which look like this: `pytorch-2.0.0.dev20230107`. This is causing our [torchhub CI to fail](https://app.circleci.com/pipelines/github/pytorch/hub/2023/workflows/1fb1a4ce-17d5-45a7-b68a-1f92441072d0/jobs/2468) with the following error:

```
E           Traceback (most recent call last):
E             File "python_code/snakers4_silero-vad_vad.py", line 9, in <module>
E               model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
E             File "/home/circleci/miniconda3/lib/python3.8/site-packages/torch/hub.py", line 543, in load
E               model = _load_local(repo_or_dir, model, *args, **kwargs)
E             File "/home/circleci/miniconda3/lib/python3.8/site-packages/torch/hub.py", line 573, in _load_local
E               model = entry(*args, **kwargs)
E             File "/home/circleci/.cache/torch/hub/snakers4_silero-vad_master/hubconf.py", line 32, in silero_vad
E               if versiontuple(installed_version) < versiontuple(supported_version):
E             File "/home/circleci/.cache/torch/hub/snakers4_silero-vad_master/hubconf.py", line 20, in versiontuple
E               return tuple(map(int, (v.split('+')[0].split("."))))
E           ValueError: invalid literal for int() with base 10: 'dev20230105'
```

Would updating the version check to something that can handle the `.devXYZ` suffix? Thank you!

**Comment by snakers4** [comment]
@adamnsandle

**Comment by adamnsandle** [comment]
fixed!

**Comment by NicolasHug** [comment]
Thank you very much!
