### ISSUE TITLE
❓ Questions / Help / Support RuntimeError: Backend "soundfile" is not one of available backends: ['sox', 'sox_io'].

### ISSUE THREAD

**Issue by garymmi** [snakers4/silero-vad#32]
## ❓ Questions and Help

We have a [wiki](https://github.com/snakers4/silero-models/wiki) available for our users. Please make sure you have checked it out first.

I used torch 1.7.1, run vad example, error as below

Downloading: "https://github.com/snakers4/silero-vad/archive/master.zip" to /home/nick/.cache/torch/hub/master.zip
/data/nick/Python-3.6.3/lib/python3.6/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
Traceback (most recent call last):
  File "vad.py", line 7, in <module>
    force_reload=True)
  File "/data/nick/Python-3.6.3/lib/python3.6/site-packages/torch/hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/data/nick/Python-3.6.3/lib/python3.6/site-packages/torch/hub.py", line 396, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "/data/nick/Python-3.6.3/lib/python3.6/site-packages/torch/hub.py", line 71, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/nick/.cache/torch/hub/snakers4_silero-vad_master/hubconf.py", line 3, in <module>
    from utils_vad import (init_jit_model,
  File "/data/inck/.cache/torch/hub/snakers4_silero-vad_master/utils_vad.py", line 9, in <module>
    torchaudio.set_audio_backend("soundfile")  # switch backend
  File "/data/nick/Python-3.6.3/lib/python3.6/site-packages/torchaudio/backend/utils.py", line 47, in set_audio_backend
    f'Backend "{backend}" is not one of '
RuntimeError: Backend "soundfile" is not one of available backends: ['sox', 'sox_io'].

**Comment by garymmi** [comment]
sorry , i forget to install soundfile

**Comment by snakers4** [comment]
if you do not like soundfile for some reason please feel free to make your version of utils and change this line
- https://github.com/snakers4/silero-vad/blob/master/utils_vad.py#L9

it used to be the best backend, but now they are changing it in favour of `sox_io`, so see for yourself
it is not necessary for any means, you can just use `wave` or `scipy` for wav files

we used torch audio in case people would use some exotic formats
