### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by atsiami** [snakers4/silero-vad#333]
Hi, I am trying to run your example microphone_and_webRTC_integration.py and I am getting the following error:

Traceback (most recent call last):
  File "microphone_and_webRTC_integration.py", line 201, in <module>
    main(ARGS)
  File "microphone_and_webRTC_integration.py", line 125, in main
    (get_speech_ts,_,_, _,_, _, _) = utils
ValueError: not enough values to unpack (expected 7, got 5)
Illegal instruction: 4

Could you help me fix that?

Thanks

**Comment by PhamLeQuangNhat** [comment]
I have a same problem. Can you help me?
