### ISSUE TITLE
ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Load model from /sdcard/Download/huigu/silero_vad.onnx failed:system error number 13

### ISSUE THREAD

**Issue by jesusycs** [snakers4/silero-vad#461]
2024-06-19 17:30:13.119 24041-24041/com.example.digitalhuman E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.digitalhuman, PID: 24041
    java.lang.RuntimeException: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Load model from /sdcard/Download/huigu/silero_vad.onnx failed:system error number 13

Caused by: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Load model from /sdcard/Download/huigu/silero_vad.onnx failed:system error number 13
        at ai.onnxruntime.OrtSession.createSession(Native Method)
        at ai.onnxruntime.OrtSession.<init>(OrtSession.java:74)
        at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:236)
        at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:221)
        at com.example.digitalhuman.vad.SlieroVadOnnxModel.<init>(SlieroVadOnnxModel.java:40)

**Comment by snakers4** [comment]
It does not load on Android? Which onnx runtime version do you have? Does it load on your x86 machine with the same version?

**Comment by snakers4** [comment]
The new VAD version was released just now - https://github.com/snakers4/silero-vad/issues/2#issuecomment-2195433115.
If the issue persists with the new version, can you please open a new issue referring to this one.
Many thanks!
