### ISSUE TITLE
❓ Questions / Help / Support VADIterator with variable chunk size

### ISSUE THREAD

**Issue by bchinnari** [snakers4/silero-vad#582]
## ❓ Questions and Help

I see VADIterator class in silero-vad.
Does it only work with 256, 512 samples only. I am getting as follows 

```
>>> x=[0]*720
>>> vad_iterator = VADIterator(model, sampling_rate=16000)
>>> speech_dict = vad_iterator(x, return_seconds=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bhargav/miniconda3/envs/faster_whisper/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/bhargav/miniconda3/envs/faster_whisper/lib/python3.9/site-packages/silero_vad/utils_vad.py", line 456, in __call__
    speech_prob = self.model(x, self.sampling_rate).item()
  File "/Users/bhargav/miniconda3/envs/faster_whisper/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/bhargav/miniconda3/envs/faster_whisper/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
torch.jit.Error: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/vad/model/vad_annotator.py", line 26, in forward
    if _2:
      _3 = torch.format(_0, (torch.size(x0))[-1])
      ops.prim.RaiseException(_3, "builtins.ValueError")
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    else:
      pass

Traceback of TorchScript, original code (most recent call last):
  File "/home/keras/notebook/nvme1/adamnsandle/silero-models-research/vad/model/vad_annotator.py", line 480, in forward
        num_samples = 512 if sr == 16000 else 256
        if x.shape[-1] != num_samples:
            raise ValueError(f"Provided number of samples is {x.shape[-1]} (Supported values: 256 for 8000 sample rate, 512 for 16000)")
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    
        batch_size = x.shape[0]
builtins.ValueError: Provided number of samples is 720 (Supported values: 256 for 8000 sample rate, 512 for 16000)
```

**Comment by snakers4** [comment]
For v5 this is done by design - the VAD accepts only fixed chunk sizes, which are short enough to be usable. 

If you need some custom buffering / interpolation logic - you will have to implement it yourself.

**Comment by bchinnari** [comment]
Previous versions of silero-vad worked with variable chunk sizes ?

**Comment by snakers4** [comment]
Yes, I believe 3 different chunk sizes were supported.

**Comment by Gldkslfmsd** [comment]
> For v5 this is done by design - the VAD accepts only fixed chunk sizes, which are short enough to be usable.
> 
> If you need some custom buffering / interpolation logic - you will have to implement it yourself.

I implemented it: https://github.com/ufal/whisper_streaming/commit/6e80c9dea8fd5887d48240428629876bc79a94b9
